# slam_config.yaml
slam_toolbox:
  ros__parameters:
    # Robot frame setup
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    
    # SLAM parameters
    use_sim_time: false
    min_laser_range: 0.1  # Instead of 0.0
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    map_update_interval: 5.0  # Publier la carte toutes les 5 secondes
    transform_timeout: 0.2
    
    # Mapping options
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    resolution: 0.05
